var lib = require('./exercises.js');
console.log('sumArgs(2,3,4) returns %d', lib.sumArgs(2,3,4));
console.log('sumArgsWhile("2",4,5) returns %d', lib.sumArgsWhile("2",4,5));
console.log('sumArgsImproved("2",4,5) returns %d', lib.sumArgsImproved('2', 4, 5));
console.log('Is 67 a prime number?  %s', lib.isPrime(67));
console.log('Is 68 a prime number?  %s', lib.isPrime(68));
console.log('Is 7 within [1, 2, 3, 4]? %s', lib.searchNum([1,2,3,4], 7));
console.log('Is 2 within [1, 2, 3, 4]? %s', lib.searchNum([1,2,3,4], 2));
console.log('If I\'m 9 I can see which movies? %o', lib.whatMovies(9));
console.log('If I\'m 39 I can see which movies? %o', lib.whatMovies(39));
console.log('If I\'m 9 I can see which movies? %o', lib.whatMoviesSwitch(9));
console.log('If I\'m 39 I can see which movies? %o', lib.whatMoviesSwitch(39));
console.log(lib.numDups([2,5,6,2,3,4,5]));
console.log('Reverse the string "Hello there I\'m backwards." %s', lib.reverseWords('Hello there I\'m backwards.'));
console.log(lib.reverseWords("Pirate Johnson"));
console.log('Reverse the string "Reverse this with a while loop." %s', lib.reverseWordsWhile('Reverse this with a while loop.'));
